### ISSUE TITLE
Zoom scales problem with ostiles database

### ISSUE THREAD

**Issue by codebrane** [OrdnanceSurvey/openspace-android-sdk#10]
I have a working app that can display the OV0, OV1 and OV2 sample data in sample.ostiles. However, when I extract the tiles and recreate the database, when I use that one, the app crashes. The two databases are the same apart from the product codes.

The recreated database causes the app to crash in:
uk.co.ordnancesurvey.android.maps.MapScrollController
where it tries to access zoomScales[0]

Does zoom scales depend on product codes? I renamed the product codes in the recreated database as there is no way to know what they are. e.g. instead of OV1, OV2, OV3 I have Z1, Z2, Z3 but the tiles table is identical. The zoom_levels table is identical too apart from the product_code values.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.codebrane.osdemo/com.codebrane.osdemo.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; in
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
    at android.app.ActivityThread.access$800(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
    at uk.co.ordnancesurvey.android.maps.MapScrollController.setZoomScales(MapScrollController.java:98)
    at uk.co.ordnancesurvey.android.maps.GLMapRenderer.setMapLayers(GLMapRenderer.java:299)

**Comment by jsr-software** [comment]
Hi, 

the product code matrix is fixed with each product code mapped to a particular set of parameters. Each code has it's own zoom level bounds and as such you cannot have two codes with the same parameters.

The mapview doesn't understand any other codes so does not know how to render them. 

There are two way to address this:
1) Match the offline db codes to one of the codes in the map layer file.
https://github.com/OrdnanceSurvey/openspace-android-sdk/blob/master/OSMapAndroid/src/main/java/uk/co/ordnancesurvey/android/maps/MapLayer.java#L72-L123

2) Create a new code in MapLayer and compile a forked version of the library. This code will need to have the correct tile sizes, zoom levels etc or it will not render.

**Comment by codebrane** [comment]
thanks for that, that's good to know about MapLayers. cheers
